export const ActionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_IMAGES: "FETCH_IMAGES",
    SET_AUTH_STATE: "SET_AUTH_STATE",
    FETCH_CATEGORIES: "FETCH_CATEGORIES"
}
